# Generated by Django 3.1.7 on 2021-03-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('description', models.CharField(max_length=200, verbose_name='Состав')),
                ('price', models.PositiveIntegerField(max_length=50, verbose_name='Цена')),
                ('portion', models.CharField(choices=[('0.7', '0.7'), ('1', '1')], max_length=50, verbose_name='Порция')),
            ],
        ),
    ]
