# Generated by Django 3.1.7 on 2021-03-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
