# Generated by Django 3.1.7 on 2021-03-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210317_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='date_start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
