# Generated by Django 3.1.7 on 2021-03-19 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_oser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='oser',
            new_name='order',
        ),
    ]
