# Generated by Django 3.1.7 on 2021-03-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20210319_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='user',
        ),
    ]
