# Generated by Django 3.1.7 on 2021-03-29 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_auto_20210329_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_type',
        ),
    ]
