# Generated by Django 3.1.7 on 2021-03-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_remove_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='order_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
