# Generated by Django 3.1.7 on 2021-04-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_employeeprofile_order_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
